###
//Get all posts
GET http://localhost:3000/posts

###
//Get post by a sender
GET http://localhost:3000/posts?sender=Hila

###
//Get post by post-id
GET http://localhost:3000/posts/676199d857d75c1e8feff0f6

###
//Create a post
POST  http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My First post",
    "content": "This is my first post",
    "sender": "Shlomit"
}

###
//Update a post by post-id
PUT http://localhost:3000/posts/676199d857d75c1e8feff0f6
Content-Type: application/json

{
    "sender": "Shlomit",
    "title": "My Third Post",
    "content": "This is my third post"
}

### 
//Delete a post by post-id
DELETE http://localhost:3000/posts/677d1f3799ff8da881d49933

###
//Get all comments
GET http://localhost:3000/comments

###
//Create a comment by post-id
POST http://localhost:3000/comments
Content-Type: application/json

{
  "comment": "This is a new comment",
  "author": "Elrom",
  "postId": "677d26b94d1ca29c0712e304"
}

###
//Get comment by post-id
GET http://localhost:3000/comments?postId=677d26b94d1ca29c0712e304

### 
//Update a comment by comment-id
PUT http://localhost:3000/comments/677d1f38a7e944aaea628355
Content-Type: application/json

{
  "comment": "Updated comment",
  "author": "Hila"
}

### 
//Delete a comment by comment-id
DELETE http://localhost:3000/comments/675f18c87a86be02491c19a0

###
//Register a new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "Hila4194@gmail.com",
    "password": "123456"
}